apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
        tier: registry
    spec:
      containers:
      - name: registry
        image: library/registry:2.6
        command: ["/bin/sh", "/etc/docker/registry/init"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 443
        - containerPort: 5001
        volumeMounts:
        - name: registry-config
          mountPath: /etc/docker/registry
          readOnly: true
        - name: certificates
          mountPath: /certificates
          readOnly: true
      volumes:
      - name: certificates
        secret:
          secretName: certificates
      - name: registry-config
        secret:
          secretName: registry-config
