apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
    tier: registry
spec:
  type: NodePort
  # type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: registry
    tier: registry
