apiVersion: v1
kind: Service
metadata:
  name: portus
  labels:
    app: portus
    tier: registry
spec:
  type: NodePort
  # type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: portus
    tier: registry
